#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Jul 25 18:07:39 IST 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim TEST_behav -key {Behavioral:sim_1:Functional:TEST} -tclbatch TEST.tcl -view /home/shubhankar/TVLSI/TEST_behav.wcfg -log simulate.log"
xsim TEST_behav -key {Behavioral:sim_1:Functional:TEST} -tclbatch TEST.tcl -view /home/shubhankar/TVLSI/TEST_behav.wcfg -log simulate.log

